branch-defaults:
  master:
    environment: my-newamerica-dev
global:
  application_name: my-newamerica
  default_ec2_keyname: atlas
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git